#!/bin/bash

shopt -s dotglob

cwd = $(pwd)

unlinkFiles() {
  from=$cwd
  if [ -n $1 ]; then
    from=$from/$1
  fi
  from=$from/*
  to=${2:-~}
  for file in $from
  do
    name=$(basename $file)
    if [ -h $to/$name ]; then
      echo "Removing $to/$name"
      unlink $to/$name
      if [ -e $to/$name~ ]; then
        echo "Restoring original"
        mv $to/$name~ $to/$name
      fi
    fi
  done
}

unlinkFiles home

echo "Removing $cwd/.vim"
unlink $cwd/.vim
echo "Restoring original"
mv ~/.vim~ ~/.vim

echo "Removing $cwd/.tmux"
unlink $cwd/.tmux
echo "Restoring original"
mv ~/.tmux~ ~/.tmux

shopt -u dotglob
