call determined#command('Npm', 'npm', { 'vertical': 0, 'autoclose': 1, 'rows': '5', 'cols': '40%' })
call determined#command('Repl', 'node', { 'background': 0 })
call determined#command('Node', 'node', { 'background': 0, 'vertical': 0, 'rows': '10', 'cols': '40%' })
call determined#command('Rg', 'rg', { 'background': 0, 'complete': replete#byArg('Rg', ['replete#complete#bufwords', 'file']) })
call determined#command('Grunt', 'grunt', { 'reuse': 1 })
call determined#command('Gulp', 'gulp', { 'reuse': 1 })
